apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deployers.deploy.example.com
spec:
  group: deploy.example.com
  names:
    kind: Deployer
    listKind: DeployerList
    plural: deployers
    singular: deployer
    shortNames:
      - deployer
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
