apiVersion: deploy.example.com/v1alpha1
kind: Deployer
metadata:
  name: nginx
spec:
  type: canary
  deployment:
    name: nginx
    namespace: default
    image: nginx
    version: 1.7.7
    labels:
      app: nginx
      operator: deployer
    replicas: 10
  steps:
    - percent: 10
      sleep: 60
    - percent: 30
      sleep: 30
    - percent: 60
      sleep: 30
    - percent: 100
