apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: do-not-sleep
  name: do-not-sleep
  namespace: sleepme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-not-sleep
  strategy: {}
  template:
    metadata:
      labels:
        app: do-not-sleep
    spec:
      containers:
      - image: davidebianchi/echo-service
        name: echo-service
        resources: {}
status: {}
