apiVersion: v1
kind: Service
metadata:
  name: hello-service2
  labels:
    app: hello2
spec:
  type: ClusterIP
  selector:
    app: hello2
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP