apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fauzan
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: training
  hostPath:
    path: /mnt/data