apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    aplikasi: frontend
  name: nginx-lab-1
  namespace: training
spec:
  replicas: 3
  selector:
    matchLabels:
      aplikasi: frontend
  template:
    metadata:
      labels:
        aplikasi: frontend
    spec:
      containers:
      - image: nginx
        name: nginx