apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-johan
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-johan
  # storageClassName: longhorn